/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    IconLocalIconsBackground: typeof import('~icons/local-icons/background')['default']
    IconLocalIconsHeadName: typeof import('~icons/local-icons/head-name')['default']
    IconLocalIconsLine: typeof import('~icons/local-icons/line')['default']
    IconLocalIconsMenu: typeof import('~icons/local-icons/menu')['default']
    IconLocalIconsName: typeof import('~icons/local-icons/name')['default']
    IconLocalIconsRound: typeof import('~icons/local-icons/round')['default']
    IconLocalIconsSearch: typeof import('~icons/local-icons/search')['default']
    IconLocalIconsWave: typeof import('~icons/local-icons/wave')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
